# Generated by Django 3.1.3 on 2020-12-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images', verbose_name='Şəkil'),
        ),
    ]
